import datetime
import enum
from types import TracebackType
from typing import Any, Final, SupportsIndex, TypeVar, final, overload
import uuid

from typing_extensions import Self
from _typeshed import structseq, SupportsLenAndGetItem, StrOrBytesPath

_Timestamp = TypeVar("_Timestamp", int, datetime.timedelta)
_Bootid = TypeVar("_Bootid", bytes, uuid.UUID)

__version__: Final[str]

class OpenFlag(enum.IntFlag):
    LOCAL_ONLY = ...
    RUNTIME_ONLY = ...
    SYSTEM = ...
    CURRENT_USER = ...
    OS_ROOT = ...
    ALL_NAMESPACES = ...
    INCLUDE_DEFAULT_NAMESPACE = ...
    TAKE_DIRECTORY_FD = ...
    ASSUME_IMMUTABLE = ...
    SYSTEM_ONLY = ...

LOCAL_ONLY = OpenFlag.LOCAL_ONLY
RUNTIME_ONLY = OpenFlag.RUNTIME_ONLY
SYSTEM = OpenFlag.SYSTEM
CURRENT_USER = OpenFlag.CURRENT_USER
OS_ROOT = OpenFlag.OS_ROOT
ALL_NAMESPACES = OpenFlag.ALL_NAMESPACES
INCLUDE_DEFAULT_NAMESPACE = OpenFlag.INCLUDE_DEFAULT_NAMESPACE
TAKE_DIRECTORY_FD = OpenFlag.TAKE_DIRECTORY_FD
ASSUME_IMMUTABLE = OpenFlag.ASSUME_IMMUTABLE
SYSTEM_ONLY = OpenFlag.SYSTEM_ONLY

class WakeupEventType(enum.IntEnum):
    NOP = ...
    APPEND = ...
    INVALIDATE = ...

NOP = WakeupEventType.NOP
APPEND = WakeupEventType.APPEND
INVALIDATE = WakeupEventType.INVALIDATE

def _get_catalog(id: str, /) -> str: ...

class _Reader:
    @overload
    def __init__(self,
                 flags: SupportsIndex = LOCAL_ONLY,
                 *,
                 files: SupportsLenAndGetItem[StrOrBytesPath | SupportsIndex]) -> None: ...
    @overload
    def __init__(self,
                 flags: SupportsIndex = LOCAL_ONLY,
                 *,
                 namespace: StrOrBytesPath) -> None: ...
    @overload
    def __init__(self,
                 flags: SupportsIndex = LOCAL_ONLY,
                 path: StrOrBytesPath | SupportsIndex | None = None,
                 files: None = None,
                 namespace: None = None) -> None: ...
    def fileno(self) -> int: ...
    def reliable_fd(self) -> bool: ...
    def get_events(self) -> int: ...
    def get_timeout(self) -> int | None: ...
    def get_timeout_ms(self) -> int: ...
    def close(self) -> None: ...
    def get_usage(self) -> int: ...
    def __enter__(self) -> Self: ...
    def __exit__(self,
                 exc_type: type[BaseException] | None,
                 exc_value: BaseException | None,
                 traceback: TracebackType | None,
                 /) -> None: ...
    def _next(self, skip: SupportsIndex = 1, /) -> bool: ...
    def _previous(self, skip: SupportsIndex = 1, /) -> bool: ...
    def _get(self, field: str, /) -> bytes: ...
    def _get_all(self) -> dict[str, bytes | list[bytes]]: ...
    def _get_realtime(self) -> int: ...
    def _get_monotonic(self) -> Monotonic[int, bytes]: ...
    def add_match(self, match: str | bytes, /) -> None: ...
    def add_disjunction(self) -> None: ...
    def add_conjunction(self) -> None: ...
    def flush_matches(self) -> None: ...
    def seek_head(self) -> None: ...
    def seek_tail(self) -> None: ...
    def seek_realtime(self, timestamp: SupportsIndex, /) -> None: ...
    def seek_monotonic(self,
                       timestamp: SupportsIndex,
                       bootid: str | None = None,
                       /) -> None: ...
    def _get_start(self) -> int: ...
    def _get_end(self) -> int: ...
    def process(self) -> WakeupEventType: ...
    def wait(self, timeout: SupportsIndex = -1, /) -> WakeupEventType: ...
    def seek_cursor(self, cursor: str, /) -> None: ...
    def _get_cursor(self) -> str: ...
    def test_cursor(self, cursor: str, /) -> bool: ...
    def query_unique(self, query: str, /) -> set[bytes]: ...
    def enumerate_fields(self) -> set[str]: ...
    def has_runtime_files(self) -> bool: ...
    def has_persistent_files(self) -> bool: ...
    def get_catalog(self) -> str: ...
    @property
    def data_threshold(self) -> int: ...
    @data_threshold.setter
    def data_threshold(self, value: int) -> None: ...
    @property
    def closed(self) -> bool: ...

@final
class Monotonic(structseq[Any], tuple[_Timestamp, _Bootid]):
    @property
    def timestamp(self) -> _Timestamp: ...
    @property
    def bootid(self) -> _Bootid: ...
