---
# vi: ts=2 sw=2 et:
# SPDX-License-Identifier: LGPL-2.1-or-later
#
name: Build test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        python: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
          "3.13"
        ]
    name: Python ${{ matrix.python }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Configure Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install gcc libsystemd-dev
          if dpkg --compare-versions "${{ matrix.python }}" ge 3.12; then
            python -m pip install setuptools || echo "can't install setuptools"
          fi
          python -m pip install pytest sphinx

      - name: Build (Python ${{ matrix.python }})
        run: |
          set -x
          make -j
          make doc SPHINXOPTS="-W -v"

      - name: Test (Python ${{ matrix.python }})
        run: |
          make check
